### ISSUE TITLE
Support Django 3.0

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#103]
This line does not work with Django 3.0:

`from django.utils.encoding import python_2_unicode_compatible`

https://docs.djangoproject.com/en/3.0/releases/3.0/

You can import directly from six if you still need to support Python 2.

**Comment by pmburu** [comment]
Is there any fix around this issue?

**Comment by ruiqurm** [comment]
> Is there any fix around this issue?
In .\friendship\models.py
replace line 10 `from django.utils.encoding import python_2_unicode_compatible` as
`from six import python_2_unicode_compatible`

**Comment by pmburu** [comment]
@ruiqurm  Thank you very much

**Comment by MrSage** [comment]
When will these changes be available via pip? The latest release 1.8.2 still has the issue.

**Comment by fcurella** [comment]
@MrSage 've just release a new version. Sorry about the long wait!

**Comment by uri-rodberg** [comment]
> @MrSage 've just release a new version. Sorry about the long wait!

https://github.com/revsys/django-friendship/issues/110
