### ISSUE TITLE
how to create a simple view for sending request to other user 

### ISSUE THREAD

**Issue by khaldon** [revsys/django-friendship#108]
in my views.py I add that code to show all friend I should to return `render ` or what should I do exactly
and also how to linked urls, views and template together and also how can use the template that builtin in django-friendship ??  
```
def my_view(request):
    # List of this user's friends
    all_friends = Friend.objects.friends(request.user)
```

**Comment by frankwiles** [comment]
This is really a question about how to use Django in general.  You should go through the official Django tutorial to get a better understanding of how models, views, and urls all interact with each other.
