### ISSUE TITLE
Running makemigrations creates a new migration when upgrading

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#110]
When I upgrade django-friendship from 1.8.1 to 1.8.2, if I run `migrate`, I receive an error that I should run `makemigrations`. If I run `makemigrations`, a new migration is created (0004).

**Comment by uri-rodberg** [comment]
Also when I upgrade django-friendship from 1.8.1 to 1.9.0, same problem.

**Comment by fcurella** [comment]
Thanks for the report @uri-rodberg ! Would you mind submitting a PR with the missing migration?

**Comment by uri-rodberg** [comment]
> Thanks for the report @uri-rodberg ! Would you mind submitting a PR with the missing migration?

https://github.com/revsys/django-friendship/pull/111
