### ISSUE TITLE
requests list giving numbers in html file

### ISSUE THREAD

**Issue by rabsi12** [revsys/django-friendship#124]
Hi,
I am new to django. So i have a question why when i am trying to call the requests lists by using Friend.objects.unread_requests(user=request.user)    in views
and inserting this in the html 
{% friend_requests request.user %}

I am getting numbers. Can anyone assist please?
I read through the titles of the raised issues none has mentioned this so i believe it is pretty novice to solve

**Comment by frankwiles** [comment]
Hi, the included templates for those template tags just render the `FriendshipRequest` models as strings.  And they stringify to their primary key IDs, so... numbers.  

If you want to display something else, likely a link to that user's profile or something else more useful, you'll need to write your own template.  Assuming you're settings are such that your templates live in a directory called `templates/` you'd need to put your own template in `templates/friendship/templatetags/friend_requests.html`.  

The template your currently using is this one which comes with the package https://github.com/revsys/django-friendship/blob/master/friendship/templates/friendship/templatetags/friend_requests.html

**Comment by rabsi12** [comment]
Thank you very much for your reply. Wanted to actually get the names of that user. maybe i didn't mention it in the initial request. I am using links and other stuff, but got stuck on deriving the name rather than the id.
Sorry for inconvenience after closing the issue. Appreciate if you can still help on getting the name

Thank you again for your help

**Comment by frankwiles** [comment]
No worries, you'll just need to walk the ORM relationship.  That template tag gives you the output of `FriendshipRequest.objects.filter(to_user=<the current user>` so to get the names it will depend a bit on what your User model looks like, but assuming a standard Django User model it would be something along the lines of: 

```
<ul>
    {% for friend_request in friend_requests %}
        <li>{{ friend_request.from_user.first_name }} {{ friend_request.from_user.last_name }}</li>
    {% endfor %}
</ul>

**Comment by rabsi12** [comment]
Million thank you for putting up with a novice.

**Comment by frankwiles** [comment]
Sure thing, we were all beginners once!

**Comment by rabsi12** [comment]
hi again... facing some obstacles... again
I built the application with the proposed urls and with your solution up and all works fine.
But what i want is to handle all requests from 1 page, i managed to get the proper querries for sent requests, received, sent requests and all users with your help... all under one webpage.
But when it comes to getting to add and accept or reject i run in all sorts of issues.
for example under the same view i have this:
def profile(request, template_name="userprofile/profile.html"):
    username=request.user.username
    user = get_object_or_404(user_model, username=username)
    friends = Friend.objects.friends(user)
    requests = FriendshipRequest.objects.filter(to_user=request.user)
    users = user_model.objects.exclude(username=request.user)
    all_sent=Friend.objects.sent_requests(user=user)

   !! other_user = User.objects.get(pk=1)
   !! Friend.objects.add_friend(request.user, other_user)
    messages.success(request, 'Membership request accepted for ')


    return render(request, template_name, {"users": users, "friend_requests": requests, "friends": friends, "all_sent": all_sent}) 
 
tried the !! parts (in views.py) with if statement and tried other like accept all resulted in errors, the one above gives 'Users cannot be friends with themselves' 
Using:
friend_request = FriendshipRequest.objects.get(to_user=1)
friend_request.accept() 
gave FriendshipRequest matching query does not exist.
changing 'get' to 'filter' gives 'QuerySet' object has no attribute 'accept'

First is it doable with your application to have all commands within 1 page and when submitting the command to stay within that same page (the add, accept, or cancel request redirecting to the profile) 
If so appriciate some guidance on how. just the add friend would suffice if possible so i can figure out the rest like i did with your previous help.

**Comment by rzamarefat** [comment]
Hi frankwiles I hope you're doing well in this pandemic. I wanted to thank you for this great job
