### ISSUE TITLE
Is_blocked in Block manager not working 

### ISSUE THREAD

**Issue by ShubhamDev-AI** [revsys/django-friendship#125]
`def is_blocked(self, user1, user2):
        """ Are these two users blocked? """
        block1 = cache.get(cache_key("blocks", user1.pk))
        block2 = cache.get(cache_key("blocks", user2.pk))
        if block1 and user2 in block1:
            return True
        elif block2 and user1 in block2:
            return True
        else:
            try:
                Block.objects.get(blocker=user1, blocked=user2)
                return True
            except Block.DoesNotExist:
                return False
`
i recently installed this package in my site but it's working properly and i get error 
**error:**
  var = Block.objects.get(blocker=user1.pk, blocked=user.pk)
AttributeError: 'int' object has no attribute 'pk'

**Comment by frankwiles** [comment]
Sounds like you're passing in a user primary key integer and not the Django User ORM object.
