### ISSUE TITLE
Friends Caching Issue!

### ISSUE THREAD

**Issue by HannanKamran001** [revsys/django-friendship#127]
I'm having issues with the 'get friends' api. When a user sends a request to another user and he accepts it, it doesn't get reflect instantly if we fetch the current friends of a user using this snippet 'Friend.objects.friends(request.user)' although in database I can see the updated results.
After 2-3 mins, it starts showing the correct results and everything works fine but within those 2-3 mins, sometimes it shows the result and sometimes it doesn't. I tried to resolve it by busting the cache through this 'bust_cache('friends', request.user.id)' but its not working either.
I believe there is an issue with the caching that this package is doing internally because on my end, I'm not using any caching mechanism to cache the DRF endpoints.

Any help would be appreciated. Thanks!

**Comment by acjh** [comment]
Can you share how to reproduce this? It's tested here:

https://github.com/revsys/django-friendship/blob/f1dd6bc7726ba2fa7f09cd5695c22671a7824e46/friendship/tests/tests.py#L107-L121
