### ISSUE TITLE
Change README to explain accepting requests better.

### ISSUE THREAD

**Issue by hvitis** [revsys/django-friendship#139]
I had an issue where I couldn't accept request because there was more than one request made by other users.
The current docs says:
```
Let the user who received the request respond:
```
But there is rarely a situation where he will receive only one request ever. 
In order to avoid exceptions I would change it to:
```
Let the user who received the request respond:
(he may have received more than one friendship request from different users)

from friendship.models import FriendshipRequest


friend_request = FriendshipRequest.objects.filter(from_user=other_user.id, to_user=logged_user.id).first()
friend_request.accept()
# or friend_request.reject()
```

It may be nothing but would have saved me a couple of min.

Thanks

**Comment by frankwiles** [comment]
Actually I think what you'd want there is more like this: 

```
requests = FriendshipRequest.objects.filter(to_user=logged_user.id)
for r in requests:
    r.accept()
```

But you're right, I'll make the example in the README more clear.
