### ISSUE TITLE
Check if Friend request exists

### ISSUE THREAD

**Issue by t3chstop** [revsys/django-friendship#148]
It would be nice to have a function to check if a friend request exists between two users. It would be like the are_friends method for checking if two users are friends.

**Comment by jefftriplett** [comment]
Can you explain what this would look like? 

In theory, we have the `are_frields` method (which you mentioned) that is accessible to the Friend model through the Friendship Manager. We could add a helper on the Friend model, but that pass `self` into that same method call.
