### ISSUE TITLE
`pip install --upgrade django-friendship` installs django-friendship-1.9.2

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#158]
```
$ pip install --upgrade django-friendship
Collecting django-friendship
  Using cached django_friendship-1.9.2-py2.py3-none-any.whl (36 kB)
Installing collected packages: django-friendship
Successfully installed django-friendship-1.9.2
(.venv_3.6)
```

**Comment by uri-rodberg** [comment]
```
$ pip install --upgrade django-friendship --no-cache-dir
Collecting django-friendship
  Downloading django_friendship-1.9.2-py2.py3-none-any.whl (36 kB)
Installing collected packages: django-friendship
Successfully installed django-friendship-1.9.2
(.venv_3.6)
```

**Comment by frankwiles** [comment]
Weird, 1.9.3 is listed as latest.  
![CleanShot Google Chrome 2021-10-04 at 13 47 01](https://user-images.githubusercontent.com/144159/135907049-e1cbe8ee-5ac4-4cd2-8560-f827c55c3db5.png)

Any chance this is related to some of your recent changes to setup.cfg?

**Comment by jefftriplett** [comment]
@frankwiles actually, yes and there is apparently an open ticket for it here: https://github.com/peritus/bumpversion/issues/198

More importantly, I migrated the config back so that bumpversion doesn't get confused. Feel free to roll another release and/or give me access and I can Tuesday.

**Comment by frankwiles** [comment]
Ok I made a new release, which shows on pypi web UI, but still getting 1.9.2 from pip. I'm going to give it a bit to see if it's a caching issue in Warehouse.

**Comment by uri-rodberg** [comment]
`pip install --upgrade django-friendship` installed for me django-friendship-1.9.4. Closing.
