### ISSUE TITLE
Officially support Django 4.1, 4.2 and Python 3.11 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#177]

**Comment by jefftriplett** [comment]
This is done but waiting on the package to be published to PyPI. https://github.com/revsys/django-friendship/blob/main/setup.cfg#L21

**Comment by uri-rodberg** [comment]
> This is done but waiting on the package to be published to PyPI. https://github.com/revsys/django-friendship/blob/main/setup.cfg#L21

PyPI supports Django 4.0 and Python 3.10. At least keep this issue open until you support Django 4.1, 4.2 and Python 3.11 on PyPI.

**Comment by frankwiles** [comment]
Think this was just an oversight on numbers, I just merged in texts and Trove for 4.2

**Comment by uri-rodberg** [comment]
At least keep this issue open until you support Django 4.1, 4.2 and Python 3.11 on PyPI.

**Comment by frankwiles** [comment]
@uri-rodberg would you be interested in taking over the maintenance of this package? You seem to be one of the heavier users of it.

**Comment by uri-rodberg** [comment]
> @uri-rodberg would you be interested in taking over the maintenance of this package? You seem to be one of the heavier users of it.

OK, I agree. Send me the details by email and give me the relevant permissions.

My email address is on my homepage, https://www.speedysoft.com/uri/en/

**Comment by uri-rodberg** [comment]
Hi, please open this issue and keep it open until a version that supports these versions of Django and Python is released to PyPI.

@frankwiles
