### ISSUE TITLE
Migration warning

### ISSUE THREAD

**Issue by alexington** [revsys/django-friendship#39]
Hi, just wanted to let you guys know about the following deprecation warning when running `migrate` or `makemigrations` on Django 1.7.  It also appears on each restart of the Django development server.

    $ ./manage.py makemigrations
	/Users/alexington/.virtualenvs/project/lib/python2.7/site-packages/friendship/migrations/0001_initial.py:14: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
	  user_model_label = '%s.%s' % (User._meta.app_label, User._meta.module_name)

Thanks for the helpful app.

**Comment by stringsonfire** [comment]
I didn't get this, so I assume it's fixed?

**Comment by alexington** [comment]
I'm no longer getting the warning.  I've upgraded to Django 1.8 so perhaps that was the reason.
