### ISSUE TITLE
Reversed arguments in Friend.objects.remove_friend()

### ISSUE THREAD

**Issue by geezhawk** [revsys/django-friendship#47]
The remove_friend method uses a query to check for friend requests in both directions with the from_user and to_user arguments. But unlike the other methods, that have a method signature like this:
`Friend.objects.add_friend(from_user, to_user)`
remove_friend's method signature looks like this:
`Friend.objects.remove_friend(to_user, from_user)`
I don't see that reversing the order of the arguments from the norm serves any purpose in this case. If you agree I'll submit a PR.

**Comment by frankwiles** [comment]
Yeah that's a good point.  Feel free to submit a PR!

**Comment by frankwiles** [comment]
As you probably well know you fixed this some time ago. I just merged it in.  Thanks!
