### ISSUE TITLE
is there a way to check if another user is being followed?

### ISSUE THREAD

**Issue by addsimm** [revsys/django-friendship#50]
Sorry for using the issue tracker; however, if this has not been implemented as a method or template tag, I will do so. Adam

**Comment by frankwiles** [comment]
It actually exists already.  If you're using Friendship (aka the Friend model) then you just need to use the manager method `Friend.objects.are_friends()` and if you're doing a Twitter Follower method (aka the Follow model) then you need to use `Follow.objects.follows()`.

**Comment by addsimm** [comment]
Thanks!
