### ISSUE TITLE
Friends, How can we know if a user follows some other user in django templates.

### ISSUE THREAD

**Issue by ams134man** [revsys/django-friendship#51]
I want to be able to do something like this:

    {% for u in users %}
        {% if follows request.user u %}
           <a href="/unfollow/{{ u.username }}">Unfollow</a>
       {% else %}
            <a href="/follow/{{ u.username }}">Follow</a>
       {% endif %}
    {% endfor %}

Please help me out.

**Comment by frankwiles** [comment]
You'll need to either write your own template tag or simply provide whether `request.user` follows the currently displayed user `u` via your own views.
