### ISSUE TITLE
Friendship Cache

### ISSUE THREAD

**Issue by niuguoning** [revsys/django-friendship#61]
I'm using the REST Api using the DRF to send friend requests, accept friend requests, and get all friends.  After I accept the friend request, I immediate pull all friends for that user; however, it doesn't show the updated list of friends.  After a couple of seconds, it finally updates with the actual results.  At the same time, when I look at the django admin, it looks like the friends have already been updated pretty instantaneously.  I don't think this is an issue with the django-friendship code, but I'm not really sure what's going on.  Any help would be greatly appreciated.  Thanks!

**Comment by frankwiles** [comment]
Hmmm, well we do cache the results and [bust them](https://github.com/revsys/django-friendship/blob/master/friendship/models.py#L61) after changes happen. 

But assuming you wait for the response from the accept and then pull a list you should get the updated results.  Unless of course you have something caching the DRF endpoints too, like Varnish or nginx maybe?

**Comment by niuguoning** [comment]
Hi Frank,

Thanks for the reply.  I modified the code and got rid of the caching mechanism and it seems to be working.  Not exactly sure what caused the issue.
