### ISSUE TITLE
Question about naming model Friend and its fields

### ISSUE THREAD

**Issue by kochnev** [revsys/django-friendship#64]
Hello! 
To be honest, I'm confused, why did you name model for representing friendship between two users like "Friend". For me, "Friendship" is more proper name for that. 
What do  "user_to" and "user_from" mean? I understand how this app works, but I can't get used to these names of fields.

What the right way to think of name of that model and its fields?

**Comment by frankwiles** [comment]
In retrospect it probably should have been named 'Friendship' was probably overly concerned on the length of the model name there. 

`to_user` and `from_user` are named after the initial request.  So if User PK#47 requested friendship with User PK#52, then User PK#47 would be the `from_user` and User PK#52 would be the `to_user`.
