### ISSUE TITLE
Proper way to remove sent request between two users?

### ISSUE THREAD

**Issue by banagale** [revsys/django-friendship#66]
I'm trying to properly remove a sent friend request between two users. (Friendship is in request state still, not complete)

If I simply delete the FriendshipRequest: ` FriendshipRequest.objects.filter(from_user=request.user, to_user=user).delete()`

The cache is not cleared.  It appears I need to call `bust_cache('sent_requests', from_user.pk)` after this to be able to get an properly updated list of sent friend requests.

However, it appears that bust_cache is not available to FriendshipManager.

What is the appropriate way to remove a sent requests where the sent_requests cache is properly updated?
  
My workaround for this is to not test the contents of the sent_requests list, and instead query FriendRequests directly.

**Comment by frankwiles** [comment]
Most of the time people want to just reject them rather than delete them, but you can do it like you said and then you just need to import bust_cache and I'd probably update all of the caches like this:

```
from friendship.models import bust_cache, FriendshipRequest

def delete_request(from_user, user):
    FriendshipRequest.objects.filter(from_user=from_user, user=user).delete()
     # Bust requests cache - request is deleted
     bust_cache('requests', from_user.pk)
     bust_cache('sent_requests', from_user.pk)
     # Bust reverse requests cache - reverse request might be deleted
     bust_cache('requests', user.pk)
     bust_cache('sent_requests', user.pk)
```

**Comment by banagale** [comment]
Thanks for this, Frank. 

Ya, the reason for this request is so that the user who _sent_ the request can cancel their open friend request. (When viewing another user's profile, there is a button that toggles from Send Friend Request to Cancel Friend Request) 

Is that strange? If this is a weird UX pattern or there is yet a more appropriate way to accomplish this than as described above please let me know.

**Comment by frankwiles** [comment]
Nope, I just don't think anyone has come to me with that use case before.  I can see how as a user I might want to delete/cancel a request I sent, it just hasn't come up for us before. 

I think your best bet right now is to use the above or submit a PR to implement it directly into friendship.
