### ISSUE TITLE
Support Django 2.0

### ISSUE THREAD

**Issue by urievenchen** [revsys/django-friendship#68]
I tried to upgrade Django to 2.0.1 and received an exception from django-friendship: 

lib\site-packages\friendship\models.py", line 73, in FriendshipRequest
    from_user = models.ForeignKey(AUTH_USER_MODEL, related_name='friendship_requests_sent')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

Can you please fix to support Django 2.0?

**Comment by bd21** [comment]
This can be fixed by adding the "on_delete=models.CASCADE" field to every location referenced when you try to run migrate.  This is because Django 2.0+ requires on_delete behavior to be explicitly defined.
