### ISSUE TITLE
Blocking features

### ISSUE THREAD

**Issue by tjcrowley** [revsys/django-friendship#72]
I've written in a Block User feature that is like the opposite of Followers. Would you be interested in this?

**Comment by frankwiles** [comment]
Oh yeah I can see that being useful to lots of people!

**Comment by tjcrowley** [comment]
I'll get it finalized and do a pull request later tonight.

**Comment by tjcrowley** [comment]
Just created pull request. I'll see if there's anything to fix in the morning. Thanks!

**Comment by frankwiles** [comment]
Released in v.1.6.0
