### ISSUE TITLE
Version 1.6.0 - manage.py makemigrations creates a new migration

### ISSUE THREAD

**Issue by urievenchen** [revsys/django-friendship#76]
manage.py makemigrations creates a new migration (with Django 1.11.13) which throws an exception when trying to migrate. Anyway manage.py makemigrations should not create new migrations. I'm downgrading to version 1.5.0.

**Comment by fcurella** [comment]
dupe of #74

**Comment by urievenchen** [comment]
Still not working in version 1.7.0.
