### ISSUE TITLE
Bug in BlockManager

### ISSUE THREAD

**Issue by berkanteber** [revsys/django-friendship#80]
Currently, the documentation says that the list of a user's blockers can be obtained as follows:
```
Block.objects.blockers(request.user)
```

However, there is no `blockers` function in `BlockManager`. When I looked at the code, I've seen a `blocked` function that should suppose to do that. This function is below:

```
def blocked(self, user):
        """ Return a list of all blocks """
        key = cache_key('blocked', user.pk)
        blocked = cache.get(key)

        if blocked is None:
            qs = Block.objects.filter(blocked=user).all()
            blocked = [u.blocked for u in qs]
            cache.set(key, blocked)

        return blocked
```

As seen it first filters `Block` objects with `blocked=user`, then takes `u.blocked` for every `u` in `qs`. As a result, we obtain a list consisting of `user`s. Instead, a list consisting of `u.blocker`s should be returned.

**Comment by umbertov** [comment]
`blocked()`, as I understand, should return a list of all the people who have blocked the given user (as `Block.objects.filter(blocked=user)` implies), but the returned value `blocked` is constructed with `u.blocked`. Now, if I'm not wrong, constructing a list with `[u.blocked for u in qs]`, with `qs` being a queryset such that `blocked=user`, should be the same as writing `[user for _ in qs]`. 

My guess is that what they meant was to return `[u.blocker for u in qs]`. But we'll have to wait until one of the devs responds...
