### ISSUE TITLE
Using Signals emitted by Django-friendship

### ISSUE THREAD

**Issue by rishav00a** [revsys/django-friendship#85]
Hello Everyone,
 I am newbie in Django. Can anyone give any example of usin signals emitted by Django-friendship in Websocket Consumer

**Comment by frankwiles** [comment]
Do you mean a consumer in django-channels? I'm not entirely sure, but this looks like how you would approach that: 

https://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers
