### ISSUE TITLE
Is can_request_send method correct?

### ISSUE THREAD

**Issue by hisyatokaku** [revsys/django-friendship#86]
The code below seems to check if request can be sent from 'from_user' to 'to_user'

```   
    def can_request_send(self, from_user, to_user):
        """ Checks if a request was sent """
        if from_user == to_user or FriendshipRequest.objects.filter(
            from_user=from_user,
            to_user=to_user,
            ).exists() is False:
            return False
        else: 
            return True
```

The method returns False when the request from 'from_user' to 'to_user' has NOT been made yet, which seems to be opposite.
Should `is False` be changed to `is True` ? 

https://github.com/revsys/django-friendship/blob/master/friendship/models.py

**Comment by uri-rodberg** [comment]
>         if from_user == to_user or FriendshipRequest.objects.filter(
>             from_user=from_user,
>             to_user=to_user,
>             ).exists() is False:

I recommend to use parentheses because it's not clear what `is False` refers to.

Also, maybe `not` is better than `is False`.

**Comment by uri-rodberg** [comment]
In this case maybe you should just remove `is False`?

**Comment by uri-rodberg** [comment]
```
        if self.can_request_send(from_user, to_user):
            raise AlreadyExistsError("Friendship already requested")

```

I'm also not sure if this code is correct.

**Comment by umbertov** [comment]
It should be
```
    if from_user == to_user or not FriendshipRequest.objects.filter(
        from_user=from_user,
        to_user=to_user,
        ).exists():
```
And 
```
if not self.can_request_send:
    raise  AlreadyExistsError (...)
```
Pardon formatting errors I'm on my phone

If somebody with write rights sees this maybe he can do the commit

**Comment by uri-rodberg** [comment]
https://github.com/revsys/django-friendship/pull/88

**Comment by umbertov** [comment]
Is this library still maintained?

**Comment by uri-rodberg** [comment]
> Is this library still maintained?

Last commit more than 3 months ago. But I'm not sure.

**Comment by frankwiles** [comment]
@hisyatokaku yes the method is correct.  I just refactored it a bit to make it slightly more clear.
