### ISSUE TITLE
@uri-rodberg that’s not how it works.

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#90]
@uri-rodberg that’s not how it works.

Your PR was merged in about a month, which is IMHO is a totally acceptable time frame in open source.

I don’t know why you think you can demand first-class support for a software you’re not paying for.

_Originally posted by @fcurella in https://github.com/revsys/django-friendship/pull/88#issuecomment-496007929_

**Comment by uri-rodberg** [comment]
> @uri-rodberg that’s not how it works.
> 
> Your PR was merged in about a month, which is IMHO is a totally acceptable time frame in open source.
> 
> I don’t know why you think you can demand first-class support for a software you’re not paying for.
> 
> _Originally posted by @fcurella in [#88 (comment)](https://github.com/revsys/django-friendship/pull/88#issuecomment-496007929)_

It's not about timing. My pull request was completely ignored.

**Comment by frankwiles** [comment]
Hi @uri-rodberg , your pull request was not "completely ignored" it was accidentally overlooked.  I saw the Issue with a request to refactor that method, so I did. Then I saw your PR which was a slightly different refactor and some PEP8 cleanup, which I had also just taken care of with Black. 

Thanks for mentioning the `create_user` kwarg order issue, I just pushed up a fix for that as well.

**Comment by uri-rodberg** [comment]
@frankwiles OK.
