### ISSUE TITLE
what url shows the list of user's friends 

### ISSUE THREAD

**Issue by ibrahimsamson** [revsys/django-friendship#91]

**Comment by frankwiles** [comment]
This [url pattern](https://github.com/revsys/django-friendship/blob/master/friendship/urls.py#L27-L31) is the view you're looking for.  The itself [is here](https://github.com/revsys/django-friendship/blob/master/friendship/views.py#L26-L37). 

Hope that helps!

**Comment by ibrahimsamson** [comment]
thanks for help
