### ISSUE TITLE
Use better __str__ for the admin interface

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#96]
Hi,

I had to modify `__str__` methods for the admin interface. Currently I'm using:

```python
class Friend:
    def __str__(self):
        return "User {} is friends with {}".format(self.to_user, self.from_user)

class FriendshipRequest:
    def __str__(self):
        return "Friendship request from user {} to {}".format(self.from_user, self.to_user)
```

You might want to update the `__str__` methods in your own models.

(We are not using your Block and Follow models).

**Comment by jefftriplett** [comment]
I left some notes in #149, but I'm closing this until we re-think what we want the role of the admin to be. I'm not sure that str repr's are a good solution, but triggering two database lookups is probably not want we want either when we evaluate the model representation.
